### ISSUE TITLE
 Failed to register delegates

### ISSUE THREAD

**Issue by picatextra** [X-CASH-official/XCASH_DPOPS#13]
When calling delegate_register from the wallet CLI ,
the error is  `Failed to register the delegate`.

On the XCASH_DPOPS , we can see Invalid message.
`validate_data()` function exit at line 924
because messages types _from wallet CLI to nodes_ are missing.

**Comment by picatextra** [comment]
@zachhildreth `GET /` request are rejected, also in  `validate_data()`

`curl http://127.0.0.1:18283/shareddelegateswebsitegetstatistics`

**Comment by zachhildreth** [comment]
Hi @picatextra 

### CVSS Score
### We have determined that the [CVSS score for this bug](https://nvd.nist.gov/vuln-metrics/cvss/v3-calculator?vector=AV:L/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:N/CR:L/IR:L/AR:L/MAV:L/MAC:L/MPR:N/MUI:N/MS:U/MC:N/MI:N/MA:N&version=3.1) is a 0

So according to the [Bug Bounty official documentation](https://docs.xcash.foundation/contribute/bug-bounty-program) this bug qualifies for a award between $5.00 and 25.00 USD

We have calculated the final amount in USD based on the following criteria


| Question                                     | Answer  |
| -------------------------------------------- | --------------------------- |
| How long I have spent on the bug                                      | N/A |
| How often does the bug occur                                            | when the affected route was accessed |
| Was there any modification to the code to create the bug  | NO |
| Did the user provide a full code fix                                | NO |
| Did the bug have to do with multi-threading                       | NO |
| Could the tester use a debugger, static analysis or both |both|
| Are we currently in Alpha, Beta or Live implementation of DPOPS |ALPHA|

Although it was noted that after the fix it was found that the delegates and shared delegates website needed fixed as well, and this helped the price.
 

## Based on the above the team has decided that the final awarded amount will be $20.00 USD

### Please post a X-CASH Wallet address in the comments, and we will send the payment in a public transaction, post the transaction hash and then close the issue.

Thank you for helping out the DPOPS by finding this bug.

**Comment by picatextra** [comment]
XCA1ka4bXH1bnvdT8vti1S12PfyH8fJ5XDUXyNRusyMRTBfFCawywJyCV5vvG38h71GAv77WotbmwbmbJen5bQpC7GeVx8gSws

**Comment by plbgnt** [comment]
### **Bounty Paid** ✅ 
--------------
**Date:** 2019-03-12
**Amount (USD):** $20
**Amount (XCASH):** 681782.98 XCASH
**Spot Price:** 0.0000293348480972966 USD/XCASH
**XCASH Address:** XCA1ka4bXH1bnvdT8vti1S12PfyH8fJ5XDUXyNRusyMRTBfFCawywJyCV5vvG38h71GAv77WotbmwbmbJen5bQpC7GeVx8gSws 
**Tx Hash:** 62bd5ffc86a0d2d2fafc92534bff1698af3a36db8c3ea63d0a51d4a34c0952c3 
**Link:** https://explorer.x-cash.org/Transaction?data=62bd5ffc86a0d2d2fafc92534bff1698af3a36db8c3ea63d0a51d4a34c0952c3
